spring:
  datasource:
    url: 'jdbc:mariadb://localhost:3306/swsdatabase'
    username: 'root'
    password: 'root'
    driver-class-name: 'org.mariadb.jdbc.Driver'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
    ddl-auto: validate
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'SwS-app'
  resource: 'SwS-app-client'
  public-client: true




